# Generated by Django 3.1.1 on 2020-10-20 23:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=120)),
                ('escolaridad', models.CharField(blank=True, choices=[('N', 'Ninguna'), ('P', 'Primaria'), ('S', 'Secundaria'), ('B', 'Bachillerato'), ('L', 'Licenciatura'), ('M', 'Maestría'), ('D', 'Doctorado')], max_length=120)),
                ('etnicidad', models.CharField(blank=True, choices=[('I', 'Indio Americano / Nativo de Alasca'), ('N', 'Negro / Afroamericano'), ('M', 'Mexicano/Americano'), ('B', 'Blanco'), ('A', 'Asiático'), ('P', 'Isleño del Pacífico / Hawaiano'), ('O', 'Otro'), ('NS', 'No lo sé')], max_length=120)),
                ('nacionalidad', django_countries.fields.CountryField(max_length=2)),
                ('fechaIngresoDeExtrangero', models.DateField(verbose_name='Fecha de ingreso a México')),
                ('estado', models.CharField(blank=True, max_length=120)),
                ('estadoCivil', models.CharField(blank=True, choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorsiado'), ('V', 'Viudo')], max_length=120)),
                ('situacionLaboral', models.CharField(blank=True, choices=[('M', 'Empleo de medio tiempo'), ('C', 'Empleo de tiempo completo'), ('D', 'Desempleo'), ('M', 'Empleo de medio tiempo'), ('I', 'Trabaja por cuenta propia'), ('E', 'Estudiante'), ('R', 'Retirado')], max_length=120)),
                ('ocupacion', models.CharField(blank=True, max_length=120)),
                ('lugarTrabajo', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolucion', models.CharField(blank=True, choices=[('T', 'En tratamiento'), ('H', 'Hospitalizado'), ('D', 'Defuncion'), ('S', 'Seguimiento domicilario'), ('R', 'Recuperado')], max_length=10)),
                ('fechaDefuncion', models.DateField(blank=True, null=True)),
                ('fechaIngresoHospital', models.DateField(blank=True, null=True)),
                ('fechaEgresoHospital', models.DateField(blank=True, null=True)),
                ('requiereOxigeno', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('requiereVentilacion', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('complicacionHospital', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cual', models.CharField(blank=True, max_length=200)),
                ('intensidad', models.CharField(blank=True, choices=[('A', 'Asintomatico'), ('M', 'Moderado'), ('L', 'Leve'), ('S', 'Severo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='viajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salioDelPais', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('paicesVisitados', models.CharField(blank=True, max_length=500)),
                ('fechaRegreso', models.DateField(blank=True, null=True, verbose_name='Fecha de regreso a México')),
                ('paciente', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='tratamientoCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('nombreMedicamento', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Antiviral'), ('1', 'Antibiotico'), ('2', 'Antiparacitario'), ('3', 'Antipirético'), ('4', 'Esteroideo'), ('5', 'Otro')], max_length=200)),
                ('fechaInicio', models.DateField(blank=True, null=True)),
                ('dosis', models.CharField(blank=True, max_length=200)),
                ('frecuencia', models.CharField(blank=True, max_length=200)),
                ('ruta', models.CharField(blank=True, choices=[('OR', 'Oral'), ('IV', 'Intravenosa'), ('IM', 'Intramuscular'), ('OT', 'Otro')], max_length=15)),
                ('fechaTermino', models.DateField(blank=True, null=True)),
                ('quienIndico', models.CharField(blank=True, choices=[(0, 'Medico'), (1, 'Familiar'), (2, 'Vecino'), (3, 'Amigo'), (4, 'Automedicación'), (5, 'Otro')], max_length=15)),
                ('quien', models.CharField(blank=True, max_length=200)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='sintomasCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiebre', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('tos', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dolorArticular', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dolorCabeza', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dolorToracico', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('conjuntivitis', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dolorGarganta', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('debilidad', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('vomito', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('malestarGeneral', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dificltadRespirar', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('perdidaGusto', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('perdidaOlfato', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('secrecionNasal', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('otras', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('irritabilidad', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('escalofrios', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cuantos', models.IntegerField(blank=True, null=True)),
                ('fechaSintomas', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de síntomas')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sintomas', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='seguridadSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguridad', models.CharField(blank=True, choices=[('0', 'IMSS'), ('1', 'ISSSTE'), ('2', 'PEMEX'), ('3', 'Defensa Nacional o Marina'), ('4', 'Seguro Popular'), ('5', 'Seguro Privado'), ('6', 'Otro'), ('7', 'Ninbguno')], max_length=10)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguridadSocial', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='seguimeinto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimeinto', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='pruebas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruebas', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('fechaSintomas', models.DateField(blank=True, null=True)),
                ('resultadoPCR', models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo'), ('I', 'Indeterminada')], max_length=10)),
                ('igg', models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo'), ('I', 'Indeterminada')], max_length=10)),
                ('igm', models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo'), ('I', 'Indeterminada')], max_length=10)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='morbilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morbilidad', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('diabetes', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('epoc', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('obesidad', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('asma', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('inmunosupresion', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cancer', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('vih', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('tuberculosis', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('otras', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('insuficienciRenal', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('hipertension', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cuales', models.CharField(blank=True, max_length=500)),
                ('trastornoNeurologico', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cardiovascular', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='morbilidades', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='habitosSaludables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frutas', models.CharField(blank=True, max_length=10)),
                ('verduras', models.CharField(blank=True, max_length=10)),
                ('pescado', models.CharField(blank=True, max_length=10)),
                ('granos', models.CharField(blank=True, max_length=10)),
                ('bebidasAzucar', models.IntegerField(blank=True, null=True)),
                ('sal', models.CharField(blank=True, max_length=10)),
                ('acitivadModerada', models.CharField(blank=True, max_length=10)),
                ('acitivadEnergetica', models.CharField(blank=True, max_length=10)),
                ('fuma', models.CharField(blank=True, choices=[('No', 'No fumo'), ('1cs', 'Un cegarrillo por semana'), ('0.5s', 'Media cajetilla a la semana'), ('1s', 'Una cajetilla a la semana'), ('1-5d', '1 a 5 cigarrillos por día'), ('0.5d', 'Media cajetilla diaria'), ('1d', 'Una cajetilla al día')], max_length=10)),
                ('anosFumando', models.CharField(blank=True, max_length=10)),
                ('indiceTabaquico', models.CharField(blank=True, max_length=10)),
                ('alcohol', models.CharField(blank=True, choices=[('0', 'Ninguna'), ('1', '1 vez'), ('2', '2 veces'), ('3-5', '3-5 veces'), ('6-9', '6-9 veces'), ('10+', '10 o más')], max_length=10)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='embarazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embarazo', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('numerodeMeses', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('postparto', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('mesesPostparto', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embarazos', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(blank=True, null=True)),
                ('fechaCuestioario', models.DateField(null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuestioarios', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='antecedentesEpidimiologicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactoCovid', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('relacion', models.CharField(blank=True, max_length=100)),
                ('quien', models.CharField(blank=True, max_length=100)),
                ('viaje', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('paciente', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='pacientes.paciente')),
            ],
        ),
    ]
