# Generated by Django 3.1.1 on 2020-10-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='estado',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estadoCivil',
            field=models.CharField(blank=True, choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorsiado'), ('V', 'Viudo')], max_length=120, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fechaIngresoDeExtrangero',
            field=models.DateField(blank=True, verbose_name='Fecha de ingreso a México'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='lugarTrabajo',
            field=models.CharField(blank=True, max_length=120, verbose_name='Lugar de trabajo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='situacionLaboral',
            field=models.CharField(blank=True, choices=[('M', 'Empleo de medio tiempo'), ('C', 'Empleo de tiempo completo'), ('D', 'Desempleo'), ('M', 'Empleo de medio tiempo'), ('I', 'Trabaja por cuenta propia'), ('E', 'Estudiante'), ('R', 'Retirado')], max_length=120, verbose_name='Situación laboral actual'),
        ),
    ]
