# Generated by Django 3.1.1 on 2020-10-22 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20201021_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pruebas',
            old_name='fechaInicio',
            new_name='fechaInicioPruebas',
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamento', to='pacientes.paciente'),
        ),
    ]
