# Generated by Django 3.1.1 on 2020-10-05 16:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20200917_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentesepidimiologicos',
            name='ciudad',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='antecedentesepidimiologicos',
            name='contactoCovid',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='antecedentesepidimiologicos',
            name='paciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='antecedentesepidimiologicos',
            name='relacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='antecedentesepidimiologicos',
            name='viaje',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='folio',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='embarazo',
            name='embarazo',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='embarazo',
            name='numerodeMeses',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='embarazo',
            name='postparto',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='acitivad',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='bebidasAzucar',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='carne',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='cigarrosAlDia',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='frutas',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='fuma',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='horasSueno',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='vecesAzucar',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='verduras',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='asma',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='cancer',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='cardiovascular',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='cuales',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='epoc',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='hipertension',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='inmunosupresion',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='insuficienciRenal',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='morbilidad',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='obesidad',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='otras',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='trastornoNeurologico',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='tuberculosis',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='vih',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='escolaridad',
            field=models.CharField(blank=True, choices=[('N', 'Ninguna'), ('P', 'Primaria'), ('S', 'Secundaria'), ('B', 'Bachillerato'), ('L', 'Licenciatura'), ('M', 'Maestría'), ('D', 'Doctorado')], max_length=120),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='fechaSintomas',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='igg',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='igm',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='pruebas',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='resultadoPCR',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='conjuntivitis',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='cuales',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='debilidad',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='dificltadRespirar',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='dolorAbdominal',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='dolorArticular',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='dolorCabeza',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='dolorGarganta',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='dolorToracico',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='escalofrios',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='fiebre',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='gusto',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='irritabilidad',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='malestarGeneral',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='mejoriaSintomas',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='olfato',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='otras',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='secrecionNasal',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='sochechaCovid19',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='tos',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='vomito',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tratamientocovid',
            name='dosis',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tratamientocovid',
            name='fechaInicio',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tratamientocovid',
            name='fechaTermino',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tratamientocovid',
            name='frecuencia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tratamientocovid',
            name='nombreMedicamento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tratamientocovid',
            name='otro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tratamientocovid',
            name='quienIndico',
            field=models.CharField(blank=True, choices=[(0, 'Medico'), (1, 'Familiar'), (2, 'Vecino'), (3, 'Amigo'), (4, 'Automedicación'), (5, 'Otro')], max_length=15),
        ),
        migrations.AlterField(
            model_name='tratamientocovid',
            name='ruta',
            field=models.CharField(blank=True, choices=[('O', 'Oral'), ('IV', 'Intravenosa'), ('IM', 'Intramuscular'), ('O', 'Otro')], max_length=15),
        ),
        migrations.AlterField(
            model_name='tratamientocovid',
            name='tratamiento',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='fechaRegreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de regreso a México'),
        ),
    ]
