# Generated by Django 3.1.1 on 2020-10-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20201022_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='nombreMedicamento',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Nombre del medicamento'),
        ),
    ]
