# Generated by Django 3.1.1 on 2020-10-05 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20201005_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentesepidimiologicos',
            name='paciente',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuestioarios', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='embarazo',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embarazos', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='morbilidades', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sintomas', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='tratamientocovid',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='paciente',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='pacientes.paciente'),
        ),
    ]
