# Generated by Django 3.1.1 on 2020-10-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20201023_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morbilidad',
            name='insuficienciRenal',
        ),
        migrations.AddField(
            model_name='morbilidad',
            name='insuficiencaiRenal',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Insuficiencia Renal'),
        ),
        migrations.AlterField(
            model_name='antecedentesepidimiologicos',
            name='relacion',
            field=models.CharField(blank=True, choices=[(0, 'Familiar'), (1, 'Amigo'), (2, 'Compañero de trabajo'), (3, 'Pareja'), (4, 'Otro')], max_length=100, verbose_name='¿Cuál es su relación con esta(s) persona(s)?'),
        ),
        migrations.AlterField(
            model_name='datosgralpaciente',
            name='etnicidad',
            field=models.CharField(blank=True, choices=[('I', 'Indio Americano / Nativo de Alaska'), ('N', 'Negro / Afroamericano'), ('M', 'Mexicano / Americano'), ('B', 'Blanco'), ('A', 'Asiático'), ('P', 'Isleño del Pacífico / Hawaiano Nativo'), ('O', 'Otro'), ('NS', 'No lo sé')], max_length=120, verbose_name='Raza / Etnia'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='bebidasAzucar',
            field=models.IntegerField(blank=True, choices=[('1', 'Si'), ('0', 'No'), ('3', 'No sé')], null=True, verbose_name='¿Bebe menos de 1 litro de bebidas azucaradas a la semana?'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='cualddroga',
            field=models.CharField(blank=True, choices=[('M', 'Marihuana'), ('C', 'Cocaína'), ('Me', 'Metanfetamina'), ('E', 'Éxtasis'), ('H', 'Heroína'), ('O', 'Otro')], max_length=10, verbose_name='Si su respuesta fue sí, especifique ¿Cuál?'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='frutas',
            field=models.CharField(blank=True, max_length=10, verbose_name='¿Cuánta fruta come en un día común y corriente?(Tazas)'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='granos',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No'), ('3', 'No sé')], max_length=10, verbose_name='¿Consume 2 o más porciones de gra a la semana?'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='pescado',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No'), ('3', 'No sé')], max_length=10, verbose_name='¿Consume 100 gramos o mas de granos enteros al día?'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='sal',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No'), ('3', 'No sé')], max_length=10, verbose_name='Actualmente, ¿Está usted moderando o reduciendo su consumo de sal o sodio?'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='verduras',
            field=models.CharField(blank=True, max_length=10, verbose_name='¿Cuánta verdura come en un día común y corriente?(Tazas)'),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='cancer',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Cáncer'),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='cuales',
            field=models.CharField(blank=True, max_length=500, verbose_name='¿Cuáles?'),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='epoc',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='EPOC'),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='hipertension',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Hipertensión'),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='inmunosupresion',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Inmunosupresión'),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='trastornoNeurologico',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Transtorno Neurológico'),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='vih',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='VIH/SIDA'),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='fechaInicioPruebas',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha dela prueba'),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='igg',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=10, verbose_name='IgG'),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='igm',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=10, verbose_name='IgM'),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='pruebas',
            field=models.CharField(blank=True, choices=[(0, 'RT-PCR'), (1, 'Prueba Rapida')], max_length=10, verbose_name='Tipo de prueba realizada'),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='resultadoRapida',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo'), ('I', 'Indeterminada')], max_length=10, verbose_name='Resultado de la prueba (Rápida)'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='cual',
            field=models.CharField(blank=True, max_length=200, verbose_name='¿Cuál?'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='evolucion',
            field=models.CharField(blank=True, choices=[('T', 'En tratamiento'), ('H', 'Hospitalizado'), ('D', 'Defunción'), ('S', 'Seguimiento domiciliario'), ('R', 'Recuperado')], max_length=10, verbose_name='Evolución de la enfermedad'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fechaEgresoHospital',
            field=models.DateField(blank=True, null=True, verbose_name='En caso de hospitalización, fecha de egreso'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='requiereVentilacion',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Requerimiento de ventilación mecánica'),
        ),
        migrations.AlterField(
            model_name='seguridadsocial',
            name='seguridad',
            field=models.CharField(blank=True, choices=[('0', 'IMSS'), ('1', 'ISSSTE'), ('2', 'PEMEX'), ('3', 'Defensa Nacional o Marina'), ('4', 'Seguro Popular'), ('5', 'Seguro Privado'), ('6', 'Otro'), ('7', 'Ninguno')], max_length=10, verbose_name='¿Qúe seguridad social tiene?'),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='cuantos',
            field=models.IntegerField(blank=True, null=True, verbose_name='¿Cuántos de estos síntomas ha presentado?'),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='salioDelPais',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Realizó viajes al extranjero en los últimos 3 meses?'),
        ),
    ]
