# Generated by Django 3.1.1 on 2020-10-21 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_auto_20201021_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgralpaciente',
            name='paciente',
            field=models.OneToOneField(default=0.1, on_delete=django.db.models.deletion.CASCADE, related_name='generales', to='pacientes.paciente'),
            preserve_default=False,
        ),
    ]
