# Generated by Django 3.1.1 on 2020-10-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_auto_20201005_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitossaludables',
            name='vasosAgua',
            field=models.IntegerField(blank=True),
        ),
    ]
