# Generated by Django 3.1.1 on 2020-10-12 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_auto_20201012_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='folio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='embarazo',
            name='numerodeMeses',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='cigarrosAlDia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='vasosAgua',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
