# Generated by Django 3.1.1 on 2020-10-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_auto_20201029_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitossaludables',
            name='bebidasAzucar',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No'), ('3', 'No sé')], max_length=10, null=True, verbose_name='¿Bebe menos de 1 litro de bebidas azucaradas a la semana?'),
        ),
    ]
