# Generated by Django 3.1.1 on 2020-10-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_auto_20201030_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebas',
            name='pruebas',
            field=models.CharField(blank=True, choices=[('0', 'RT-PCR'), ('1', 'Prueba Rapida')], max_length=10, verbose_name='Tipo de prueba realizada'),
        ),
    ]
