# Generated by Django 3.1.1 on 2021-01-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_auto_20201030_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebas',
            name='resultadoAntigeno',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo'), ('I', 'Indeterminada')], max_length=10, verbose_name='Resultado de la prueba (Antigeno)'),
        ),
        migrations.AlterField(
            model_name='antecedentesepidimiologicos',
            name='relacion',
            field=models.CharField(blank=True, choices=[('0', 'Familiar'), ('1', 'Amigo'), ('2', 'Compañero de trabajo'), ('3', 'Pareja'), ('4', 'Otro')], max_length=100, verbose_name='¿Cuál es su relación con esta(s) persona(s)?'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='quienIndico',
            field=models.CharField(blank=True, choices=[('0', 'Medico'), ('1', 'Familiar'), ('2', 'Vecino'), ('3', 'Amigo'), ('4', 'Automedicación'), ('5', 'Otro')], max_length=15, verbose_name='¿Quién indicó el tratamiento?'),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='pruebas',
            field=models.CharField(blank=True, choices=[('0', 'RT-PCR'), ('1', 'Prueba Rapida'), ('1', 'Prueba Antigeno')], max_length=10, verbose_name='Tipo de prueba realizada'),
        ),
    ]
