# Generated by Django 3.1.1 on 2020-10-21 23:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=120)),
                ('nacionalidad', django_countries.fields.CountryField(max_length=2)),
                ('fechaIngresoDeExtrangero', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso a México')),
            ],
        ),
        migrations.CreateModel(
            name='viajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salioDelPais', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Realizó viajes al extrangjero en los últimos 3 meses?')),
                ('paicesVisitados', models.CharField(blank=True, max_length=500, verbose_name='En caso de ser sí su respuesta anterior, ¿qué países visitó?')),
                ('fechaRegreso', models.DateField(blank=True, null=True, verbose_name='¿En que fecha ingresó a México?')),
                ('paciente', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='tratamientoCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Desde el inicio de los signos/síntomas ha tomado algún tratamiento?')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='sintomasCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiebre', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('tos', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dolorArticular', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Dolor articular')),
                ('dolorCabeza', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Dolor de cabeza')),
                ('dolorToracico', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Dolor torácico')),
                ('conjuntivitis', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dolorGarganta', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Dolor de garganta al tragar')),
                ('debilidad', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('vomito', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Vómito')),
                ('malestarGeneral', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Malestar general')),
                ('dificltadRespirar', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Dificultad para respirar')),
                ('perdidaGusto', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Pérdida del sentido del gusto')),
                ('perdidaOlfato', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Pérdida del sentido del olfato')),
                ('secrecionNasal', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Secreción nasal')),
                ('otro', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('irritabilidad', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('escalofrios', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Escalofríos')),
                ('cuantos', models.IntegerField(blank=True, null=True, verbose_name='¿Cuántos de estos sintomas ha presentado?')),
                ('mejoria', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Ha tenido mejoría en la presentación de los signos o síntomas?')),
                ('fechaSintomas', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de síntomas')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sintomas', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='seguridadSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguridad', models.CharField(blank=True, choices=[('0', 'IMSS'), ('1', 'ISSSTE'), ('2', 'PEMEX'), ('3', 'Defensa Nacional o Marina'), ('4', 'Seguro Popular'), ('5', 'Seguro Privado'), ('6', 'Otro'), ('7', 'Ninbguno')], max_length=10, verbose_name='¿Qúe seguridad social tiene?')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguridadSocial', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolucion', models.CharField(blank=True, choices=[('T', 'En tratamiento'), ('H', 'Hospitalizado'), ('D', 'Defuncion'), ('S', 'Seguimiento domicilario'), ('R', 'Recuperado')], max_length=10, verbose_name='Evolución de la enfermedad')),
                ('fechaDefuncion', models.DateField(blank=True, null=True, verbose_name='En caso de deunción, fecha de defunción')),
                ('fechaIngresoHospital', models.DateField(blank=True, null=True, verbose_name='En caso de hospitalización, fecha de ingreso')),
                ('fechaEgresoHospital', models.DateField(blank=True, null=True, verbose_name='En caso de deunción, fecha de egreso')),
                ('requiereOxigeno', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Requerimiento de oxígeno')),
                ('requiereVentilacion', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Requerimiento de ventilación mecánic')),
                ('complicacionHospital', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Complicaciones hospitalarias')),
                ('cual', models.CharField(blank=True, max_length=200)),
                ('intensidad', models.CharField(blank=True, choices=[('A', 'Asintomatico'), ('M', 'Moderado'), ('L', 'Leve'), ('S', 'Severo')], max_length=10)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='pruebas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruebas', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Tipo de prueba realizada')),
                ('fechaInicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('resultadoPCR', models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo'), ('I', 'Indeterminada')], max_length=10, verbose_name='Resultado de la prueba (RT-PCR)')),
                ('resultadoRapida', models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=10, verbose_name='Resultado de la prueba (Rápida)')),
                ('igg', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('igm', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='morbilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morbilidad', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Presenta alguna morbilidad?')),
                ('diabetes', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('epoc', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('obesidad', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('asma', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('inmunosupresion', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cancer', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('vih', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('tuberculosis', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('insuficienciRenal', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('hipertension', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('trastornoNeurologico', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cardiovascular', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('otras', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cuales', models.CharField(blank=True, max_length=500, verbose_name='¿Cuales?')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='morbilidades', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMedicamento', models.CharField(blank=True, max_length=200, verbose_name='Nombre del medicamento')),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Antiviral'), ('1', 'Antibiotico'), ('2', 'Antiparacitario'), ('3', 'Antipirético'), ('4', 'Esteroideo'), ('5', 'Otro')], max_length=200)),
                ('fechaInicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('dosis', models.CharField(blank=True, max_length=200)),
                ('frecuencia', models.CharField(blank=True, max_length=200)),
                ('ruta', models.CharField(blank=True, choices=[('OR', 'Oral'), ('IV', 'Intravenosa'), ('IM', 'Intramuscular'), ('OT', 'Otro')], max_length=15, verbose_name='Ruta de administración')),
                ('fechaTermino', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('quienIndico', models.CharField(blank=True, choices=[(0, 'Medico'), (1, 'Familiar'), (2, 'Vecino'), (3, 'Amigo'), (4, 'Automedicación'), (5, 'Otro')], max_length=15, verbose_name='¿Quién indicó el tratamiento?')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamento', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='habitosSaludables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frutas', models.CharField(blank=True, max_length=10, verbose_name='¿Cuánta fruta come en un día común y corriente?')),
                ('verduras', models.CharField(blank=True, max_length=10, verbose_name='¿Cuánta verdura come en un día común y corriente?')),
                ('pescado', models.CharField(blank=True, max_length=10, verbose_name='¿Consume 2 o más porciones de pescado a la semana?')),
                ('granos', models.CharField(blank=True, max_length=10, verbose_name='¿Consume 2 o más porciones de pescado a la semana?')),
                ('bebidasAzucar', models.IntegerField(blank=True, null=True, verbose_name='¿Bebe menos de 1 litro de bebidas azucaradas a la semana?')),
                ('sal', models.CharField(blank=True, max_length=10, verbose_name='Actualmente, ¿Está usted moderando o reduciendo su consumo de sal o sodio?')),
                ('acitivadModerada', models.CharField(blank=True, max_length=10, verbose_name='¿Cuánta actividad física moderada normalmente realiza semanalmente?')),
                ('acitivadEnergetica', models.CharField(blank=True, max_length=10, verbose_name='¿Cuánta actividad física enérgica/vigorosa realiza semanalmente?')),
                ('fuma', models.CharField(blank=True, choices=[('No', 'No fumo'), ('1cs', 'Un cegarrillo por semana'), ('0.5s', 'Media cajetilla a la semana'), ('1s', 'Una cajetilla a la semana'), ('1-5d', '1 a 5 cigarrillos por día'), ('0.5d', 'Media cajetilla diaria'), ('1d', 'Una cajetilla al día')], max_length=10, verbose_name='¿Con qué frecuencia fuma cigarrillos?')),
                ('freqFumando', models.CharField(blank=True, max_length=10, verbose_name='Tiempo en años')),
                ('indiceTabaquico', models.CharField(blank=True, max_length=10, verbose_name='Índice tabáquico')),
                ('anosFumando', models.CharField(blank=True, max_length=10, verbose_name='¿Cuánto tiempo tiene fumando?')),
                ('alcohol', models.CharField(blank=True, choices=[('0', 'Ninguna'), ('1', '1 vez'), ('2', '2 veces'), ('3-5', '3-5 veces'), ('6-9', '6-9 veces'), ('10+', '10 o más')], max_length=10, verbose_name='En los útimos 30 días ¿Cuántas veces ha tomado por lo menos cinco bebidas alcohólicas seguidas?')),
                ('drogas', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Ha consumido alguna sustancia nociva como marihuana,cocaína, mentafetamina, éxtasis?')),
                ('cualddroga', models.CharField(blank=True, choices=[('M', 'Marihuana'), ('C', 'Cocaina'), ('Me', 'Mentafetamina'), ('E', 'Éxtasis'), ('H', 'Heroina'), ('O', 'Otro')], max_length=10, verbose_name='Si su respuesta fue sí, especifique ¿Cuál?')),
                ('otradroga', models.CharField(blank=True, max_length=10, verbose_name='¿Cuál otra droga?')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='embarazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embarazo', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Está embarazada?')),
                ('numerodeMeses', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Meses de embarazo')),
                ('postparto', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Se encuentra en periodo de posparto?')),
                ('mesesPostparto', models.IntegerField(blank=True, null=True, verbose_name='Meses desde el parto')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embarazos', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='datosGralPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etnicidad', models.CharField(blank=True, choices=[('I', 'Indio Americano / Nativo de Alaska'), ('N', 'Negro / Afroamericano'), ('M', 'Mexicano / Americano'), ('B', 'Blanco'), ('A', 'Asiático'), ('P', 'Isleño del Pacífico / Hawaiano Nativo'), ('O', 'Otro'), ('NS', 'No lo sé')], max_length=120, verbose_name='Raza / Etina')),
                ('escolaridad', models.CharField(blank=True, choices=[('N', 'Ninguna'), ('P', 'Primaria'), ('S', 'Secundaria'), ('B', 'Bachillerato'), ('L', 'Licenciatura'), ('M', 'Maestría'), ('D', 'Doctorado')], max_length=120, verbose_name='Escolaridad (última terminada)')),
                ('estadoCivil', models.CharField(blank=True, choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viudo')], max_length=120, verbose_name='Estado Civil')),
                ('situacionLaboral', models.CharField(blank=True, choices=[('M', 'Empleo de medio tiempo'), ('C', 'Empleo de tiempo completo'), ('D', 'Desempleado'), ('I', 'Trabaja por cuenta propia'), ('E', 'Estudiante'), ('R', 'Retirado')], max_length=120, verbose_name='Situación laboral actual')),
                ('ocupacion', models.CharField(blank=True, max_length=120, verbose_name='Ocupación')),
                ('lugarTrabajo', models.CharField(blank=True, max_length=120, verbose_name='Lugar de trabajo')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generales', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(blank=True, null=True)),
                ('fechaCuestionario', models.DateField(null=True, verbose_name='Fecha del cuestionario')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='antecedentesEpidimiologicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactoCovid', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Ha tenido contacto con alguna persona que tenga COVID-19 en las dos últimas semanas?')),
                ('relacion', models.CharField(blank=True, max_length=100, verbose_name='¿Cuál es su relación con esta(s) persona(s)?')),
                ('viaje', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Realizó algún viaje en las últimas dos semanas?')),
                ('pais', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Si su respuesta fue sí, especifique el lugar (país y ciudad)')),
                ('paciente', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='pacientes.paciente')),
            ],
        ),
    ]
