# Generated by Django 3.1.1 on 2020-10-20 15:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=120)),
                ('escolaridad', models.CharField(blank=True, choices=[('N', 'Ninguna'), ('P', 'Primaria'), ('S', 'Secundaria'), ('B', 'Bachillerato'), ('L', 'Licenciatura'), ('M', 'Maestría'), ('D', 'Doctorado')], max_length=120)),
                ('etnicidad', models.CharField(blank=True, max_length=120)),
                ('nacionalidad', django_countries.fields.CountryField(max_length=2)),
                ('calle', models.CharField(blank=True, max_length=120)),
                ('colonia', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(blank=True, max_length=120)),
                ('cp', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=120)),
                ('ocupacion', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolucion', models.CharField(blank=True, choices=[('T', 'En tratamiento'), ('H', 'Hospitalizado'), ('D', 'Defuncion'), ('S', 'Seguimiento domicilario'), ('R', 'Recuperado')], max_length=10)),
                ('fechaDefuncion', models.DateField(blank=True, null=True)),
                ('fechaIngresoHospital', models.DateField(blank=True, null=True)),
                ('fechaEgresoHospital', models.DateField(blank=True, null=True)),
                ('requiereOxigeno', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('requiereVentilacion', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('complicacionHospital', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cual', models.CharField(blank=True, max_length=200)),
                ('intensidad', models.CharField(blank=True, choices=[('A', 'Asintomatico'), ('M', 'Moderado'), ('L', 'Leve'), ('S', 'Severo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='viajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salioDelPais', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('paicesVisitados', models.CharField(blank=True, max_length=500)),
                ('fechaRegreso', models.DateField(blank=True, null=True, verbose_name='Fecha de regreso a México')),
                ('paciente', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='tratamientoCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('quienIndico', models.CharField(blank=True, choices=[(0, 'Medico'), (1, 'Familiar'), (2, 'Vecino'), (3, 'Amigo'), (4, 'Automedicación'), (5, 'Otro')], max_length=15)),
                ('otro', models.CharField(blank=True, max_length=200)),
                ('nombreMedicamento', models.CharField(blank=True, max_length=200)),
                ('dosis', models.CharField(blank=True, max_length=200)),
                ('frecuencia', models.CharField(blank=True, max_length=200)),
                ('fechaInicio', models.DateField(blank=True, null=True)),
                ('fechaTermino', models.DateField(blank=True, null=True)),
                ('ruta', models.CharField(blank=True, choices=[('O', 'Oral'), ('IV', 'Intravenosa'), ('IM', 'Intramuscular'), ('O', 'Otro')], max_length=15)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='sintomasCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiebre', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('tos', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('escalofrios', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dolorCabeza', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dolorToracico', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dolorGarganta', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dolorAbdominal', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dolorArticular', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('debilidad', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('conjuntivitis', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('olfato', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('gusto', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dificltadRespirar', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('irritabilidad', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('vomito', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('secrecionNasal', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('malestarGeneral', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('otras', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cuales', models.CharField(blank=True, max_length=300)),
                ('mejoriaSintomas', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('sochechaCovid19', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sintomas', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='pruebas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruebas', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('fechaSintomas', models.DateField(blank=True, null=True)),
                ('resultadoPCR', models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=10)),
                ('igg', models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=10)),
                ('igm', models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=10)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='morbilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morbilidad', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('diabetes', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('epoc', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('asma', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('inmunosupresion', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('vih', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('tuberculosis', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('insuficienciRenal', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('trastornoNeurologico', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cardiovascular', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('obesidad', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('hipertension', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cancer', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('otras', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cuales', models.CharField(blank=True, max_length=500)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='morbilidades', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='habitosSaludables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frutas', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('vecesAzucar', models.IntegerField(blank=True, null=True)),
                ('carne', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('verduras', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('acitivad', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('vasosAgua', models.IntegerField(blank=True, null=True)),
                ('bebidasAzucar', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('horasSueno', models.CharField(blank=True, max_length=10)),
                ('fuma', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cigarrosAlDia', models.IntegerField(blank=True, null=True)),
                ('alcohol', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='embarazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embarazo', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('numerodeMeses', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('postparto', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embarazos', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(blank=True, null=True)),
                ('fechaCuestioario', models.DateField(null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuestioarios', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='antecedentesEpidimiologicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactoCovid', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('relacion', models.CharField(blank=True, max_length=100)),
                ('viaje', models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('ciudad', models.CharField(blank=True, max_length=300)),
                ('paciente', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='pacientes.paciente')),
            ],
        ),
    ]
