# Generated by Django 3.1.1 on 2020-09-17 23:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='calle',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='paciente',
            name='colonia',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cp',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='viajes',
            name='fechaRegreso',
            field=models.DateField(null=True, verbose_name='Fecha de regreso a México'),
        ),
        migrations.AddField(
            model_name='viajes',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='viajes',
            name='paicesVisitados',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='viajes',
            name='salioDelPais',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.CreateModel(
            name='tratamientoCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('quienIndico', models.CharField(choices=[(0, 'Medico'), (1, 'Familiar'), (2, 'Vecino'), (3, 'Amigo'), (4, 'Automedicación'), (5, 'Otro')], max_length=15)),
                ('otro', models.CharField(max_length=200)),
                ('nombreMedicamento', models.CharField(max_length=200)),
                ('dosis', models.CharField(max_length=200)),
                ('frecuencia', models.CharField(max_length=200)),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('ruta', models.CharField(choices=[('O', 'Oral'), ('IV', 'Intravenosa'), ('IM', 'Intramuscular'), ('O', 'Otro')], max_length=15)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='sintomasCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiebre', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('tos', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('escalofrios', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dolorCabeza', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dolorToracico', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dolorGarganta', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dolorAbdominal', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dolorArticular', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('debilidad', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('conjuntivitis', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('olfato', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('gusto', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('dificltadRespirar', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('irritabilidad', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('vomito', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('secrecionNasal', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('malestarGeneral', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('otras', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cuales', models.CharField(max_length=300)),
                ('mejoriaSintomas', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('sochechaCovid19', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sintomas', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='pruebas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruebas', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('fechaSintomas', models.DateField()),
                ('resultadoPCR', models.CharField(choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=10)),
                ('igg', models.CharField(choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=10)),
                ('igm', models.CharField(choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=10)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='morbilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morbilidad', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('diabetes', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('epoc', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('asma', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('inmunosupresion', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('vih', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('tuberculosis', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('insuficienciRenal', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('trastornoNeurologico', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cardiovascular', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('obesidad', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('hipertension', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cancer', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('otras', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cuales', models.CharField(max_length=500)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morbilidades', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='habitosSaludables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frutas', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('vecesAzucar', models.IntegerField()),
                ('carne', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('verduras', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('acitivad', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('vasosAgua', models.IntegerField()),
                ('bebidasAzucar', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('horasSueno', models.CharField(max_length=10)),
                ('fuma', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('cigarrosAlDia', models.IntegerField()),
                ('alcohol', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='embarazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embarazo', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('numerodeMeses', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('postparto', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embarazos', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField()),
                ('fechaCuestioario', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestioarios', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='antecedentesEpidimiologicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactoCovid', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('relacion', models.CharField(max_length=100)),
                ('viaje', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=10)),
                ('ciudad', models.CharField(max_length=300)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='pacientes.paciente')),
            ],
        ),
    ]
