# Generated by Django 3.1.1 on 2020-10-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20201021_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fechaIngresoDeExtrangero',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso a México'),
        ),
    ]
