# Generated by Django 3.1.1 on 2020-09-17 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20200917_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='paciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='paicesVisitados',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
