# Generated by Django 3.1.1 on 2020-10-21 17:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20201021_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionario',
            name='fechaCuestioario',
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='fechaCuestionario',
            field=models.DateField(null=True, verbose_name='Fecha del cuestionario'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='embarazo',
            name='embarazo',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Está emparazada?'),
        ),
        migrations.AlterField(
            model_name='embarazo',
            name='mesesPostparto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Meses desde el parto'),
        ),
        migrations.AlterField(
            model_name='embarazo',
            name='numerodeMeses',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Meses de embarazo'),
        ),
        migrations.AlterField(
            model_name='embarazo',
            name='postparto',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Se encuentra en periodo de posparto?'),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='paicesVisitados',
            field=models.CharField(blank=True, max_length=500, verbose_name='En caso de ser sí su respuesta anterior, ¿qué países visitó?'),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='salioDelPais',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Realizó viajes al extrangjero en los últimos 3 meses?'),
        ),
    ]
