# Generated by Django 3.1.1 on 2020-10-21 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20201021_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='datosGralPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolaridad', models.CharField(blank=True, choices=[('N', 'Ninguna'), ('P', 'Primaria'), ('S', 'Secundaria'), ('B', 'Bachillerato'), ('L', 'Licenciatura'), ('M', 'Maestría'), ('D', 'Doctorado')], max_length=120)),
                ('etnicidad', models.CharField(blank=True, choices=[('I', 'Indio Americano / Nativo de Alasca'), ('N', 'Negro / Afroamericano'), ('M', 'Mexicano/Americano'), ('B', 'Blanco'), ('A', 'Asiático'), ('P', 'Isleño del Pacífico / Hawaiano'), ('O', 'Otro'), ('NS', 'No lo sé')], max_length=120)),
                ('fechaIngresoDeExtrangero', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso a México')),
                ('estadoCivil', models.CharField(blank=True, choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorsiado'), ('V', 'Viudo')], max_length=120, verbose_name='Estado Civil')),
                ('situacionLaboral', models.CharField(blank=True, choices=[('M', 'Empleo de medio tiempo'), ('C', 'Empleo de tiempo completo'), ('D', 'Desempleo'), ('M', 'Empleo de medio tiempo'), ('I', 'Trabaja por cuenta propia'), ('E', 'Estudiante'), ('R', 'Retirado')], max_length=120, verbose_name='Situación laboral actual')),
                ('ocupacion', models.CharField(blank=True, max_length=120, verbose_name='Ocupación')),
                ('lugarTrabajo', models.CharField(blank=True, max_length=120, verbose_name='Lugar de trabajo')),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='escolaridad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='estadoCivil',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='etnicidad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fechaIngresoDeExtrangero',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='lugarTrabajo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='situacionLaboral',
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='paciente',
            field=models.OneToOneField(default=0.0004950495049504951, on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento', to='pacientes.paciente'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='seguimeinto',
        ),
    ]
