# Generated by Django 3.1.1 on 2020-10-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_auto_20201008_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitossaludables',
            name='vecesAzucar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
