# Generated by Django 3.1.1 on 2020-10-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_auto_20201021_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sintomascovid',
            old_name='otras',
            new_name='otro',
        ),
        migrations.RemoveField(
            model_name='tratamientocovid',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='tratamientocovid',
            name='fechaInicio',
        ),
        migrations.RemoveField(
            model_name='tratamientocovid',
            name='fechaTermino',
        ),
        migrations.RemoveField(
            model_name='tratamientocovid',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='tratamientocovid',
            name='nombreMedicamento',
        ),
        migrations.RemoveField(
            model_name='tratamientocovid',
            name='quienIndico',
        ),
        migrations.RemoveField(
            model_name='tratamientocovid',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='tratamientocovid',
            name='tipo',
        ),
        migrations.AddField(
            model_name='sintomascovid',
            name='mejoria',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Ha tenido mejoría en la presentación de los signos o síntomas?'),
        ),
        migrations.AlterField(
            model_name='embarazo',
            name='embarazo',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Está embarazada?'),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='cuantos',
            field=models.IntegerField(blank=True, null=True, verbose_name='¿Cuántos de estos sintomas ha presentado?'),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='dificltadRespirar',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Dificultad para respirar'),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='dolorArticular',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Dolor articular'),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='dolorCabeza',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Dolor de cabeza'),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='dolorGarganta',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Dolor de garganta al tragar'),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='dolorToracico',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Dolor torácico'),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='escalofrios',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Escalofríos'),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='malestarGeneral',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Malestar general'),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='perdidaGusto',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Pérdida del sentido del gusto'),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='perdidaOlfato',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Pérdida del sentido del olfato'),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='secrecionNasal',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Secreción nasal'),
        ),
        migrations.AlterField(
            model_name='sintomascovid',
            name='vomito',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Vómito'),
        ),
        migrations.AlterField(
            model_name='tratamientocovid',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='tratamientocovid',
            name='tratamiento',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Desde el inicio de los signos/síntomas ha tomado algún tratamiento?'),
        ),
        migrations.AlterField(
            model_name='viajes',
            name='fechaRegreso',
            field=models.DateField(blank=True, null=True, verbose_name='¿En que fecha ingresó a México?'),
        ),
        migrations.CreateModel(
            name='medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMedicamento', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Antiviral'), ('1', 'Antibiotico'), ('2', 'Antiparacitario'), ('3', 'Antipirético'), ('4', 'Esteroideo'), ('5', 'Otro')], max_length=200)),
                ('fechaInicio', models.DateField(blank=True, null=True)),
                ('dosis', models.CharField(blank=True, max_length=200)),
                ('frecuencia', models.CharField(blank=True, max_length=200)),
                ('ruta', models.CharField(blank=True, choices=[('OR', 'Oral'), ('IV', 'Intravenosa'), ('IM', 'Intramuscular'), ('OT', 'Otro')], max_length=15)),
                ('fechaTermino', models.DateField(blank=True, null=True)),
                ('quienIndico', models.CharField(blank=True, choices=[(0, 'Medico'), (1, 'Familiar'), (2, 'Vecino'), (3, 'Amigo'), (4, 'Automedicación'), (5, 'Otro')], max_length=15)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamento', to='pacientes.paciente')),
            ],
        ),
    ]
