# Generated by Django 3.1.1 on 2020-10-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_auto_20201012_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='fechaCuestioario',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='fechaSintomas',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tratamientocovid',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tratamientocovid',
            name='fechaTermino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
