# Generated by Django 3.1.1 on 2020-10-21 19:18

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_auto_20201021_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedentesepidimiologicos',
            name='quien',
        ),
        migrations.RemoveField(
            model_name='pruebas',
            name='fechaSintomas',
        ),
        migrations.RemoveField(
            model_name='tratamientocovid',
            name='quien',
        ),
        migrations.AddField(
            model_name='pruebas',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='antecedentesepidimiologicos',
            name='contactoCovid',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Ha tenido contacto con alguna persona que tenga COVID-19 en las dos últimas semanas?'),
        ),
        migrations.AlterField(
            model_name='antecedentesepidimiologicos',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='¿Realizó algún viaje en las últimas dos semanas?'),
        ),
        migrations.AlterField(
            model_name='antecedentesepidimiologicos',
            name='relacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='¿Cuál es su relación con esta(s) persona(s)?'),
        ),
        migrations.AlterField(
            model_name='antecedentesepidimiologicos',
            name='viaje',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Realizó algún viaje en las últimas dos semanas?'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='fechaTermino',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombreMedicamento',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='quienIndico',
            field=models.CharField(blank=True, choices=[(0, 'Medico'), (1, 'Familiar'), (2, 'Vecino'), (3, 'Amigo'), (4, 'Automedicación'), (5, 'Otro')], max_length=15, verbose_name='¿Quién indicó el tratamiento?'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='ruta',
            field=models.CharField(blank=True, choices=[('OR', 'Oral'), ('IV', 'Intravenosa'), ('IM', 'Intramuscular'), ('OT', 'Otro')], max_length=15, verbose_name='Ruta de administración'),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='pruebas',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='Tipo de prueba realizada'),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='resultadoPCR',
            field=models.CharField(blank=True, choices=[('P', 'Positivo')], max_length=10, verbose_name='Resultado de la prueba (Rápida)'),
        ),
    ]
