# Generated by Django 3.1.1 on 2020-10-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_auto_20201021_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebas',
            name='resultadoRapida',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=10, verbose_name='Resultado de la prueba (Rápida)'),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='resultadoPCR',
            field=models.CharField(blank=True, choices=[('P', 'Positivo'), ('N', 'Negativo'), ('I', 'Indeterminada')], max_length=10, verbose_name='Resultado de la prueba (RT-PCR)'),
        ),
    ]
