# Generated by Django 3.1.1 on 2020-10-21 19:46

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_auto_20201021_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitossaludables',
            name='cualddroga',
            field=models.CharField(blank=True, choices=[('M', 'Marihuana'), ('C', 'Cocaina'), ('Me', 'Mentafetamina'), ('E', 'Éxtasis'), ('H', 'Heroina'), ('O', 'Otro')], max_length=10, verbose_name='Si su respuesta fue sí, especifique ¿Cuál?'),
        ),
        migrations.AddField(
            model_name='habitossaludables',
            name='drogas',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Ha consumido alguna sustancia nociva como marihuana,cocaína, mentafetamina, éxtasis?'),
        ),
        migrations.AddField(
            model_name='habitossaludables',
            name='freqFumando',
            field=models.CharField(blank=True, max_length=10, verbose_name='Tiempo en años'),
        ),
        migrations.AddField(
            model_name='habitossaludables',
            name='otradroga',
            field=models.CharField(blank=True, max_length=10, verbose_name='¿Cuál otra droga?'),
        ),
        migrations.AlterField(
            model_name='antecedentesepidimiologicos',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Si su respuesta fue sí, especifique el lugar (país y ciudad)'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='acitivadEnergetica',
            field=models.CharField(blank=True, max_length=10, verbose_name='¿Cuánta actividad física enérgica/vigorosa realiza semanalmente?'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='acitivadModerada',
            field=models.CharField(blank=True, max_length=10, verbose_name='¿Cuánta actividad física moderada normalmente realiza semanalmente?'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('0', 'Ninguna'), ('1', '1 vez'), ('2', '2 veces'), ('3-5', '3-5 veces'), ('6-9', '6-9 veces'), ('10+', '10 o más')], max_length=10, verbose_name='En los útimos 30 días ¿Cuántas veces ha tomado por lo menos cinco bebidas alcohólicas seguidas?'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='anosFumando',
            field=models.CharField(blank=True, max_length=10, verbose_name='¿Cuánto tiempo tiene fumando?'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='bebidasAzucar',
            field=models.IntegerField(blank=True, null=True, verbose_name='¿Bebe menos de 1 litro de bebidas azucaradas a la semana?'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='frutas',
            field=models.CharField(blank=True, max_length=10, verbose_name='¿Cuánta fruta come en un día común y corriente?'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='fuma',
            field=models.CharField(blank=True, choices=[('No', 'No fumo'), ('1cs', 'Un cegarrillo por semana'), ('0.5s', 'Media cajetilla a la semana'), ('1s', 'Una cajetilla a la semana'), ('1-5d', '1 a 5 cigarrillos por día'), ('0.5d', 'Media cajetilla diaria'), ('1d', 'Una cajetilla al día')], max_length=10, verbose_name='¿Con qué frecuencia fuma cigarrillos?'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='granos',
            field=models.CharField(blank=True, max_length=10, verbose_name='¿Consume 2 o más porciones de pescado a la semana?'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='indiceTabaquico',
            field=models.CharField(blank=True, max_length=10, verbose_name='Índice tabáquico'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='pescado',
            field=models.CharField(blank=True, max_length=10, verbose_name='¿Consume 2 o más porciones de pescado a la semana?'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='sal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Actualmente, ¿Está usted moderando o reduciendo su consumo de sal o sodio?'),
        ),
        migrations.AlterField(
            model_name='habitossaludables',
            name='verduras',
            field=models.CharField(blank=True, max_length=10, verbose_name='¿Cuánta verdura come en un día común y corriente?'),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='cuales',
            field=models.CharField(blank=True, max_length=500, verbose_name='¿Cuales?'),
        ),
        migrations.AlterField(
            model_name='morbilidad',
            name='morbilidad',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10, verbose_name='¿Presenta alguna morbilidad?'),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='igg',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pruebas',
            name='igm',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('0', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='seguridadsocial',
            name='seguridad',
            field=models.CharField(blank=True, choices=[('0', 'IMSS'), ('1', 'ISSSTE'), ('2', 'PEMEX'), ('3', 'Defensa Nacional o Marina'), ('4', 'Seguro Popular'), ('5', 'Seguro Privado'), ('6', 'Otro'), ('7', 'Ninbguno')], max_length=10, verbose_name='¿Qúe seguridad social tiene?'),
        ),
    ]
